name: chatSocketServer-spigot
version: '${project.version}'
main: com.chatsocketserverspigot.ChatSocketServer_spigot
api-version: '1.16'
authors:
  - "Twiyin0"
description: "A socket chat launcher!"
commands:
  chatSocketServer:
    description: "The main command"
    permission: chatSocketServer.admin
depend:
  - PlaceholderAPI